on:
  push:
    branches:
      - "*"

name: Test react@experimental

jobs:
  test-experimental-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm@latest
      - run: pnpm i 
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - run: pnpm upgrade react@experimental react-dom@experimental

      - run: node run-tests.js --timings