on:
  push:
    branches:
      - "*"

name: Test react@next

jobs:
  test-next-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm@latest
      - run: pnpm i 
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - run: pnpm upgrade react@next react-dom@next

      - run: node run-tests.js --timings

  
